### ISSUE TITLE
SQL database

### ISSUE THREAD

**Issue by elisevmol** [elisevmol/MRWP-Project#1]
Should be possible with Panda's, maybe something to look at Johanna!
http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_sql.html

**Comment by johannak12** [comment]
MusicBrainz turns out to be XML 

Research that made a collaboration network from allmusic.com: https://arxiv.org/pdf/physics/0609229.pdf

**Another option:** 
Using the million song database, which has metadata about a million contemporary popular music tracks (including info about music features etc., also includes data from musicbrainz.com)
http://labrosa.ee.columbia.edu/millionsong/
    ---> Easier to use and includes all data we need 
    ---> Example code on their website (because format is HDF5)
    ---> We could use the 1% (= 10.000 songs) subset
